### PR TITLE
fix: throwing plug properly handled and returns 500

### LINKED ISSUE #410: Mishandled plug `throw` value
The value thrown by a plug, because is not handled by bandit, ends up being treated as the 2nd element value in an `{:ok, value}` result of `ThousandIsland.Handler.handle_connection`.

So, when I test in a plug `throw "something"`, I end up getting a `ThousandIsland.Handler` abnormal termination of reason `{:bad_return_value, "something"}`.

Digging into the call stack I realized this means that erlang's `gen_server` catches the thrown value and tries to interpret it as the value to be return by the `gen_server` callback, in this case `ThousandInsland.Handler.handle_continue`.

- gen_server [loop](https://github.com/erlang/otp/blob/44ffe8811dfcf3d2fe04d530c6e8fac5ca384e02/lib/stdlib/src/gen_server.erl#L2244-L2248)
  - [try_handle_continue](https://github.com/erlang/otp/blob/44ffe8811dfcf3d2fe04d530c6e8fac5ca384e02/lib/stdlib/src/gen_server.erl#L2333-L2341)
  - [handle_common_reply](https://github.com/erlang/otp/blob/44ffe8811dfcf3d2fe04d530c6e8fac5ca384e02/lib/stdlib/src/gen_server.erl#L2479-L2480)

This means that I was getting `:bad_return_value` just because `"something"` is an invalid value for `gen_server` callback returns. But if I `throw {:noreply, {}}` in the plug, the `gen_server` doesn't terminate, and it's state is updated to `{}` or whatever other value is returned, right?

---

For what is worth, this is the output I get when placing a few inspect statement along `bandit` and `thousand_island` while testing and debugging.

```
"======== ThousandIsland.Handler.init"
"======== ThousandIsland.Handler.handle_info"
"======== ThousandIsland.Handler.handle_continue"
"======== Bandit.DelegatingHandler.handle_connection"
"======== Bandit.DelegatingHandler.handle_bandit_continuation"
"======== Bandit.DelegatingHandler.handle_connection"
"======== Bandit.DelegatingHandler.handle_bandit_continuation"
"======== Bandit.DelegatingHandler.handle_data"
"======== Bandit.HTTP1.Handler.handle_data - calling Pipeline.run"
"======== ThousandIsland.Handler.terminate - reason: {:bad_return_value, \"something\"}"
```

### PR DESCRIPTION
**Pull request by grzuy**
closes #410.

An re-worked attempt after #396, trying to improve it by taking some pieces from #398.

### CODE REVIEW

File: lib/bandit/telemetry.ex [hunk 1]
```diff
@@ -76,8 +76,8 @@ defmodule Bandit.Telemetry do
       * `conn`: The `Plug.Conn` representing this connection. Not present in cases where `error`
         is also set and the nature of error is such that Bandit was unable to successfully build
         the conn
-      * `kind`: The kind of unexpected condition, typically `:exit`
-      * `exception`: The exception which caused this unexpected termination
+      * `kind`: The kind of unexpected condition, typically `:error` or `:throw`
+      * `reason`: The error reason. An Exception struct or the thrown value
```
Comment (mtrudel) [inline lib/bandit/telemetry.ex:80]: The rest of this PR looks great; these are the only two items I have issue with.

For better or worse, we've already baked in `exception` and `exit` in metadata, and [downstream packages](https://github.com/open-telemetry/opentelemetry-erlang-contrib/blob/main/instrumentation/opentelemetry_bandit/lib/opentelemetry_bandit.ex) already depend on them. We can't change them without a major version bump and that's not happening for this. 

I'd suggest:

* Changing `:error` back to `:exit` and `reason` back to `exception`
* Keeping `:throw` as a second valid value for`kind`
* Adding a new `:throw_value` key to pass the thrown value if it's a throw

This is enough to be backwards compatible and still have sensible semantic here I think.

**Review by mtrudel — CHANGES_REQUESTED** [review]

**Comment by grzuy** [comment]
Conflicts with `main` expected after #413 merged.
Solving soon.

File: lib/bandit/telemetry.ex (hunk 1 above)
Comment (grzuy) [reply lib/bandit/telemetry.ex:80]: Thanks for the feedback!

Sounds fair.

Related to this previous discussion, for what is worth, https://github.com/mtrudel/bandit/pull/398#discussion_r1761940338.

Will try adapt to something backwards-compatible.

**Comment by mtrudel** [comment]
let me know when this is ready to stand for review again!

File: lib/bandit/telemetry.ex (hunk 1 above)
Comment (grzuy) [reply lib/bandit/telemetry.ex:80]: After digging into `opentelemetry_bandit` I realized it might be a problem to start emitting events of `kind: :throw` right now. `opentelemetry_bandit` (actually `opentelemetry_api`) is expecting only exceptions: https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_api/lib/open_telemetry/span.ex.

The story is different for cowboy because it's using `otel_span.erl`, which actually handles gracefully different kinds (referred to as `Class` in there): https://github.com/open-telemetry/opentelemetry-erlang/blob/a506d08e8439c353bbf8277a1ca619c668d125f8/apps/opentelemetry_api/src/otel_span.erl#L239-L242. 

Rolling back for now, to only emitting the same events as before this PR and later can tackle emitting new throw events in tandem with possible updates in `opentelemetry_bandit`.

Comment (grzuy) [reply lib/bandit/telemetry.ex]: > Rolling back for now, to only emitting the same events as before this PR and later can tackle emitting new throw events in tandem with possible updates in `opentelemetry_bandit`.

https://github.com/mtrudel/bandit/pull/411/commits/e8239b612a8003f05effe657e862aa37b451b412

**Comment by grzuy** [comment]
Thank you :pray:

**Comment by mtrudel** [comment]
Thank YOU! Sorry this took so long to get sorted; i've had my hands full with real world things and am finally getting back to being able to spend some time on Bandit. Thanks for the patience.

**Comment by grzuy** [comment]
No worries!
Thanks for all your great work :100:
